### ISSUE TITLE
not working in latest firefox version

### ISSUE THREAD

**Issue by msangel** [dbaron/leak-monitor#1]
update plz....

**Comment by msangel** [comment]
And I will buy for you a cookie!

**Comment by dbaron** [comment]
The things leak-monitor did no longer make sense in the current Firefox architecture.  And, beyond that, in many cases modern Firefox automatically fixes the sorts of leaks that leak-monitor was detecting.

This repository is really here only for historical interest, and I have no plans to maintain the extension further.
